### ISSUE TITLE
Function to set knitr hooks

### ISSUE THREAD

**Issue by wlandau** [ropensci-org/roblog#44]
The [R Markdown](https://github.com/ropensci/roweb3/blob/master/archetypes/Rmd/index.md) post template begins with a large code chunk to define `knitr` hooks. Would it be convenient to wrap those hooks in an `roblog` function?

**Comment by maelle** [comment]
Thanks! I think that we didn't want every author to have to install roblog, @stefaniebutland what do you think?

**Comment by stefaniebutland** [comment]
That's correct @maelle

**Comment by wlandau** [comment]
Right, good point.

**Comment by wlandau** [comment]
I am fine with closing this issue if you are.
